/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Main.Plant;
import Main.Generator;
import javax.swing.JOptionPane;

/**
 *
 * @author luism
 */
public class addPlant extends javax.swing.JFrame {
     Plant[] plants;
    /**
     * Creates new form addPlant
     */
    public addPlant(Plant[] plants) {
        this.plants = plants;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PlantName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        engineParts = new javax.swing.JTextField();
        wheelParts = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bodyWorksParts = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        chasisParts = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        accesories = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        standardCarPrice = new javax.swing.JTextField();
        accesoriesCarPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        standardCarNumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        gennerator = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Car Assembler Plant simulator");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(377, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel2.setText("Brand Name");

        PlantName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlantNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Engine Parts Required For The Car");

        engineParts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enginePartsActionPerformed(evt);
            }
        });

        wheelParts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wheelPartsActionPerformed(evt);
            }
        });

        jLabel4.setText("Wheel Parts Required For The Car");

        bodyWorksParts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyWorksPartsActionPerformed(evt);
            }
        });

        jLabel6.setText("Chasis Parts Required For The Car");

        chasisParts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chasisPartsActionPerformed(evt);
            }
        });

        jLabel7.setText("Body Work Parts Required For The Car");

        accesories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accesoriesActionPerformed(evt);
            }
        });

        jLabel5.setText("Standard Car Price");

        standardCarPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardCarPriceActionPerformed(evt);
            }
        });

        accesoriesCarPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accesoriesCarPriceActionPerformed(evt);
            }
        });

        jLabel8.setText("Accesories Car Price");

        standardCarNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardCarNumberActionPerformed(evt);
            }
        });

        jLabel9.setText("Generator Number (Stundent ID  last digit)");

        gennerator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genneratorActionPerformed(evt);
            }
        });

        jLabel10.setText("Standard Cars Produced Before Accesories Car");

        jLabel11.setText("Accesories required For The Car");

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(engineParts, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(PlantName)
                            .addComponent(wheelParts)
                            .addComponent(bodyWorksParts)
                            .addComponent(chasisParts))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(standardCarPrice)
                            .addComponent(accesories)
                            .addComponent(accesoriesCarPrice)
                            .addComponent(standardCarNumber)
                            .addComponent(gennerator, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PlantName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(engineParts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wheelParts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bodyWorksParts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chasisParts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accesories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(standardCarPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accesoriesCarPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(standardCarNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gennerator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(submit)
                .addGap(0, 37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlantNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlantNameActionPerformed

    }//GEN-LAST:event_PlantNameActionPerformed

    private void enginePartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enginePartsActionPerformed

    }//GEN-LAST:event_enginePartsActionPerformed

    private void wheelPartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wheelPartsActionPerformed

    }//GEN-LAST:event_wheelPartsActionPerformed

    private void bodyWorksPartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyWorksPartsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bodyWorksPartsActionPerformed

    private void chasisPartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chasisPartsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chasisPartsActionPerformed

    private void accesoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accesoriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accesoriesActionPerformed

    private void standardCarPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardCarPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_standardCarPriceActionPerformed

    private void accesoriesCarPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accesoriesCarPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accesoriesCarPriceActionPerformed

    private void standardCarNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardCarNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_standardCarNumberActionPerformed

    private void genneratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genneratorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genneratorActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        
      try {
          int accesories = this.stringToIntParser(this.accesories.getText());
          int accesoriesCarPrice = this.stringToIntParser(this.accesoriesCarPrice.getText());
          int standardCarPrice = this.stringToIntParser(this.standardCarPrice.getText());
          int bodyWorksParts = this.stringToIntParser(this.bodyWorksParts.getText());
          int chasisParts = this.stringToIntParser(this.chasisParts.getText());
          int engineParts = this.stringToIntParser(this.engineParts.getText());
          int generatorNumber = this.stringToIntParser(this.gennerator.getText());
          int standardCarNumber = this.stringToIntParser(this.standardCarNumber.getText());
          int wheelParts = this.stringToIntParser(this.wheelParts.getText());
          
          Generator generator = new Generator(generatorNumber);
          Plant plant = new Plant(this.PlantName.getText(), chasisParts, engineParts, bodyWorksParts, accesories, wheelParts, standardCarPrice, accesoriesCarPrice, standardCarNumber, generator, this.plants.length);
          
          
          Plant[] newArray = new Plant[this.plants.length + 1];
          
            for (int i = 0; i < this.plants.length; i++) {
                newArray[i] = this.plants[i];
            }
            
            newArray[newArray.length - 1] = plant;
            this.plants = newArray;
            
            this.setVisible(false);
            new Interface(this.plants).setVisible(true);
      }catch (Exception e) {
          System.out.println(e);
            JOptionPane.showMessageDialog(null, "some variable can't be parse to integer.");
      }
      
        
    }//GEN-LAST:event_submitActionPerformed
   
    
    public int stringToIntParser(String arg) {
        return Integer.parseInt(arg);
        
    }
    
    public boolean gtethanzero(int arg) {
        return arg > 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PlantName;
    private javax.swing.JTextField accesories;
    private javax.swing.JTextField accesoriesCarPrice;
    private javax.swing.JTextField bodyWorksParts;
    private javax.swing.JTextField chasisParts;
    private javax.swing.JTextField engineParts;
    private javax.swing.JTextField gennerator;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField standardCarNumber;
    private javax.swing.JTextField standardCarPrice;
    private javax.swing.JButton submit;
    private javax.swing.JTextField wheelParts;
    // End of variables declaration//GEN-END:variables
}
